# Production environment
# Run ./init.sh before starting the containers
services:
  backend:
    image: ghcr.io/docker-pet/backend:latest
    container_name: backend
    restart: always
    volumes:
      - ./volumes/backend:/app/pb_data
      - ./volumes/lampa/configs:/app/lampa
    command:
      - /app/backend
      - serve
      - --http=0.0.0.0:80

  frontend:
    image: ghcr.io/docker-pet/frontend:latest
    container_name: frontend
    restart: always

  lampa:
    image: immisterio/lampac:latest
    container_name: lampa
    restart: always
    depends_on:
      - backend
    environment:
      TZ: $TZ
    volumes:
      - ./volumes/lampa/configs/init.conf:/home/init.conf
      - ./volumes/lampa/configs/manifest.json:/home/module/manifest.json:ro
      - ./volumes/lampa/configs/passwd:/home/passwd:ro
      - ./volumes/lampa/modification.js:/home/wwwroot/plugins/modification.js:ro
      - ./volumes/lampa/dlna:/home/dlna

  caddy:
    image: ghcr.io/docker-pet/caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      BASE_DOMAIN: ${BASE_DOMAIN}
    command:
      - run
      - --config
      - /etc/caddy/Caddyfile
      - --watch
    volumes:
      - ./volumes/caddy/prod/Caddyfile:/etc/caddy/Caddyfile

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300
    restart: always